### ISSUE TITLE
[BUG] Buzzheavier not working

### ISSUE THREAD

**Issue by FunsKiTo** [Official-Husko/mul-tor#24]
Buzzheavier is not working: 
`Exception: HTTPSConnectionPool(host='w.buzzheavier.com', port=443): Max retries exceeded with url: /f/filename.rar (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2423)')))`

**Comment by Official-Husko** [comment]
I'm Investigating this issue right now.

**Comment by Official-Husko** [comment]
Buzzheavier changed some domain stuff on the uploading part. Fix has been pushed in commit [a8aa9ab](https://github.com/Official-Husko/mul-tor/commit/a8aa9aba7c8fb5b1cd307843ea8817f7b554a6b4) and will be available in the next update v1.5.1.

**Comment by Official-Husko** [comment]
Fix available in release [v1.5.1](https://github.com/Official-Husko/mul-tor/releases/tag/1.5.1)
