### ISSUE TITLE
[BUG] PixelDrain slow speeds?

### ISSUE THREAD

**Issue by FunsKiTo** [Official-Husko/mul-tor#26]
I get 2MB/s speeds, compare to others that go above 50MB/s

btw, bug reports get label as enhancements

**Comment by Official-Husko** [comment]
God damnit i fucked up the issue templates.. I have seen that issue too which seems to be rather new. Before it never had this slow speed. I will investigate this.

**Comment by Official-Husko** [comment]
Speed issue has been resolved. Upload is now as fast if not faster than browser uploads. In my test a 1GB file from 5 minutes+ down to 1 minute.

**Comment by Official-Husko** [comment]
Fix available in release [v1.5.1](https://github.com/Official-Husko/mul-tor/releases/tag/1.5.1)
