### ISSUE TITLE
[BUG] Wrong name of executable after update

### ISSUE THREAD

**Issue by M4RCK5** [Official-Husko/mul-tor#35]
When the tool updates itself it renames the new executable to "Mul-Tor.exe.exe"

**Comment by Official-Husko** [comment]
> When the tool updates itself it renames the new executable to "Mul-Tor.exe.exe"

Really? God damnit. I will check it out and fix it if needed.

**Comment by M4RCK5** [comment]
> > When the tool updates itself it renames the new executable to "Mul-Tor.exe.exe"
> 
> Really? God damnit. I will check it out and fix it if needed. Thank you for reporting this.
> 
> Edit: yep it is an issue that nobody has noticed until now. will be fixed in the next release.

Having a fix for this could be usefull for people that launch the tool from an desktop shortcut for example because if it changes its name after each update the shortcut isnt going to work anymore.

**Comment by Official-Husko** [comment]
> > > When the tool updates itself it renames the new executable to "Mul-Tor.exe.exe"
> > 
> > 
> > Really? God damnit. I will check it out and fix it if needed. Thank you for reporting this.
> > Edit: yep it is an issue that nobody has noticed until now. will be fixed in the next release.
> 
> Having a fix for this could be usefull for people that launch the tool from an desktop shortcut for example because if it changes its name after each update the shortcut isnt going to work anymore.

Yea i will definitely update it. It shouldn't happen normally.

**Comment by Official-Husko** [comment]
@M4RCK5 Just a quick question, do you use the proxies or random user agent function of this tool?

**Comment by M4RCK5** [comment]
> @M4RCK5 Just a quick question, do you use the proxies or random user agent function of this tool?
> 

Not atm, but could be usefull if a site blocks mw from uploading files
