### ISSUE TITLE
[SITE REQ] bzzhr.co

### ISSUE THREAD

**Issue by M4RCK5** [Official-Husko/mul-tor#40]
**Please give me the links that apply below**
Main Website: https://bzzhr.co/
API URL: https://nul.bzzhr.co/

**Please fill out the information below:**

- [x] This site has an API
- [ ] This site requires an account
- [ ] This site is requires a subscription
- [ ] I would be willing to give a premium account to add the site

**Is there anything else you would like to add that might help me?**
Pixeldrain will require an account soon:
https://twitter.com/Fornax96/status/1795418633121706491

**Comment by Official-Husko** [comment]
Buzzheavier is already supported.
bzzhr will be added to the todo list.

thanks for the notice on pixeldrain. Once that hits i will have to make accounts mandatory.

**Comment by M4RCK5** [comment]
The site its going to be discontinued:
![image](https://github.com/Official-Husko/mul-tor/assets/20927212/4fce1438-c66d-423c-bf11-b6c6e873b5ba)

**Comment by Official-Husko** [comment]
> The site its going to be discontinued: ![image](https://private-user-images.githubusercontent.com/20927212/339650340-4fce1438-c66d-423c-bf11-b6c6e873b5ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjEzNzMsIm5iZiI6MTcxODM2MTA3MywicGF0aCI6Ii8yMDkyNzIxMi8zMzk2NTAzNDAtNGZjZTE0MzgtYzY2ZC00MjNjLWJmMTEtYjZjNmU4NzNiNWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEwMzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNzYzN2E3N2NiZWZmZTk4M2U1ZmM0OGMzOTEzNjhhZWI1NmFiNmJhM2RlM2E1OWUyZGMzNjQ2N2RiOTczZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4osmlNSxiMD8Jw3PzGL4T6aLqL1ZSpkFup--EfKDuCw)

![well thats just great gif](https://c.tenor.com/Yn1Dkq1tmLsAAAAC/tenor.gif)

I guess no bzzhr.co for us then. Thanks for the update @M4RCK5.

**Comment by M4RCK5** [comment]
@Official-Husko 
![image](https://github.com/Official-Husko/mul-tor/assets/20927212/781a4bae-0226-46a2-aaa6-3064c48ae6b9)
