### ISSUE TITLE
[REQUEST] Remove expire date when uploading to Buzzheavier.

### ISSUE THREAD

**Issue by M4RCK5** [Official-Husko/mul-tor#41]
**Is your feature request related to a problem? Please describe.**
When uploading to Buzzheavier the files expire in 4 months, what about changing it to unlimited with torrent support??

**Describe the solution you'd like**
In the devs section of their site says how to upload files without expire date and with torrent support:
curl -#o - -T "sample.mp4" "https://w.buzzheavier.com/t/sample.mp4" | cat

**Describe alternatives you've considered**
Making a little batch script just for this, i know isnt hard at all but i think it could be a good thing for Mul-Tor

- [ ] Remove Bandwith Limit
- [ ] Add Torrent Support

**Comment by M4RCK5** [comment]
Came up with this little batch script:

```
@echo off
cd /d "%~dp0"
title Buzzheavier Uploader
color 09

:start
call :title
set "file="
set /p "file=File: "

setlocal enabledelayedexpansion
for %%a in (%file%) do (
	set filename=%%~nxa
	set filename=!filename: =_!
	call :title
	echo Uploading "%%~nxa", please wait...
	echo.
	for /f "tokens=2 delims=:" %%b in ('curl.exe -T "%%~fa" "https://w.buzzheavier.com/t/!filename!"') do (
		set output=%%b
		set output=!output:"=!
		set output=!output:}=!
		set output=https://buzzheavier.com/f/!output!
		echo.
		echo !output!
		echo %date% - %time% - [!filename!](!output!^)>>BZH-Links.txt
	)
)
endlocal

echo.
if defined file pause
goto :start

:title
cls
echo.
echo ----Buzzheavier Uploader----
echo.
goto :eof
```

**Comment by Official-Husko** [comment]
> **Is your feature request related to a problem? Please describe.** When uploading to Buzzheavier the files expire in 4 months, what about changing it to unlimited with torrent support??
> 
> **Describe the solution you'd like** In the devs section of their site says how to upload files without expire date and with torrent support: curl -#o - -T "sample.mp4" "https://w.buzzheavier.com/t/sample.mp4" | cat
> 
> **Describe alternatives you've considered** Making a little batch script just for this, i know isnt hard at all but i think it could be a good thing for Mul-Tor

While reverse engineering some sites i found that either they didn't check the entered data with which i was able to abuse by entering any time i please regarding file lifetime or which had infinite time like this but i decided to not abuse these loopholes or things so i went with multiple months for all of the scripts that had some time option. What i can offer is instead of hardcoding this i could add an option for certain hosts so the user can enable it. If there is no specific need for long file lifetimes then its better if they are by default expiring after some time in my opinion.

Regarding the torrent support one. I was looking into that and while making the site script for it the feature was broken from what i have seen. The torrent file i got from it was not working it was actually an invalid file so i skipped it for the time being but since it seems to be working i can definitely add it now.

**Comment by M4RCK5** [comment]
> > **Is your feature request related to a problem? Please describe.** When uploading to Buzzheavier the files expire in 4 months, what about changing it to unlimited with torrent support??
> > **Describe the solution you'd like** In the devs section of their site says how to upload files without expire date and with torrent support: curl -#o - -T "sample.mp4" "https://w.buzzheavier.com/t/sample.mp4" | cat
> > **Describe alternatives you've considered** Making a little batch script just for this, i know isnt hard at all but i think it could be a good thing for Mul-Tor
> 
> While reverse engineering some sites i found that either they didn't check the entered data with which i was able to abuse by entering any time i please regarding file lifetime or which had infinite time like this but i decided to not abuse these loopholes or things so i went with multiple months for all of the scripts that had some time option. What i can offer is instead of hardcoding this i could add an option for certain hosts so the user can enable it. If there is no specific need for long file lifetimes then its better if they are by default expiring after some time in my opinion.
> 
> Regarding the torrent support one. I was looking into that and while making the site script for it the feature was broken from what i have seen. The torrent file i got from it was not working it was actually an invalid file so i skipped it for the time being but since it seems to be working i can definitely add it now.

Having the option for the sites that "officiali support it" could be great (i dont recommend adding the option to the ones that dont have it without reverse enginering them, it could be abused and patched later, its up to you of course)

**Comment by Official-Husko** [comment]
> > > **Is your feature request related to a problem? Please describe.** When uploading to Buzzheavier the files expire in 4 months, what about changing it to unlimited with torrent support??
> > > **Describe the solution you'd like** In the devs section of their site says how to upload files without expire date and with torrent support: curl -#o - -T "sample.mp4" "https://w.buzzheavier.com/t/sample.mp4" | cat
> > > **Describe alternatives you've considered** Making a little batch script just for this, i know isnt hard at all but i think it could be a good thing for Mul-Tor
> > 
> > 
> > While reverse engineering some sites i found that either they didn't check the entered data with which i was able to abuse by entering any time i please regarding file lifetime or which had infinite time like this but i decided to not abuse these loopholes or things so i went with multiple months for all of the scripts that had some time option. What i can offer is instead of hardcoding this i could add an option for certain hosts so the user can enable it. If there is no specific need for long file lifetimes then its better if they are by default expiring after some time in my opinion.
> > Regarding the torrent support one. I was looking into that and while making the site script for it the feature was broken from what i have seen. The torrent file i got from it was not working it was actually an invalid file so i skipped it for the time being but since it seems to be working i can definitely add it now.
> 
> Having the option for the sites that "officiali support it" could be great (i dont recommend adding the option to the ones that dont have it without reverse enginering them, it could be abused and patched later, its up to you of course)

Sounds like perfect compromise to me:
![handshake gif](https://i.giphy.com/LZ2WRdQu8udNPSZxbg.gif)

I will add it to the todo list to make sure its present in the next major 2.0 release.

**Comment by M4RCK5** [comment]
@Official-Husko sorry for bringing this up again but made some changes to the script that ive wrote before, could be a temporary solution for buzzheavier users untill Mul-Tor 2.0 comes, anyways thanks for ur great work

**Comment by Official-Husko** [comment]
From what i saw torrents are now created right out of the box for uploaded files.

**Comment by M4RCK5** [comment]
> @M4RCK5 From what i saw torrents are now created right out of the box for uploaded files. Can you confirm this?

Yeah they are, i reported some bugs related to the torrents so they should work fine now, also they added an mirror domain called flashbang.sh to bypass isp protections

**Comment by Official-Husko** [comment]
> > @M4RCK5 From what i saw torrents are now created right out of the box for uploaded files. Can you confirm this?
> 
> Yeah they are, i reported some bugs related to the torrents so they should work fine now, also they added an mirror domain called flashbang.sh to bypass isp protections

I think there are even more mirrors if I'm not wrong. Either way i have made a commit that removes the expiry date for buzzheavier. I will try to push the update today. It includes a few fixes and the pixeldrain update to get it working again.

**Comment by M4RCK5** [comment]
> > > @M4RCK5 From what i saw torrents are now created right out of the box for uploaded files. Can you confirm this?
> > 
> > Yeah they are, i reported some bugs related to the torrents so they should work fine now, also they added an mirror domain called flashbang.sh to bypass isp protections
> 
> I think there are even more mirrors if I'm not wrong. Either way i have made a commit that removes the expiry date for buzzheavier. I will try to push the update today. It includes a few fixes and the pixeldrain update to get it working again.

Yeah they added trashbytes.net yesterday.
Also about the update, ill test it whenever u release it so no rush, if i find any bug ill let u know.
