### ISSUE TITLE
clarifying rejected site: https://send.zcyph.cc/

### ISSUE THREAD

**Issue by braboobssiere** [Official-Husko/mul-tor#5]
it is part of [continuation of discontinued firefox's send](https://github.com/timvisee/send) (not by mozilla) which you can see the source code there, and is one of  [public instance](https://github.com/timvisee/send-instances)

not that I'm requesting it or anything but i feel like rejected reason need more info

**Comment by Official-Husko** [comment]
Yea i know what you mean with "needs more info". It is already fixed in the development branch. What i meant at the time was the system it uses which is some sockets wizardry stuff which i have never worked with before let alone even heard of.
